### ISSUE TITLE
CODE REQUEST FOR INTERNET BASED NAVIGATION AND CONTROL

### ISSUE THREAD

**Issue by ssg8288** [ssg8288/DEV_SCRIPT_WOC_2020#1]
@DWOC 2020 @DWOC

- [ ] arduino code for Internet based control for a crawler circuit

**Comment by aeyshubh** [comment]
I can work with this issue .

**Comment by ssg8288** [comment]
> 
> 
> I can work with this issue .

yes you can sure here you go.

**Comment by aeyshubh** [comment]
HI , I am halfway to the solution ,will comeup with the code in Five days . Sorry for the delay

**Comment by ssg8288** [comment]
> 
> 
> HI , I am halfway to the solution ,will comeup with the code in Five days . Sorry for the delay


![](https://media.tenor.com/images/a5d88d211e6579b952c671863a7feeac/tenor.gif)
