### ISSUE TITLE
 issue and pull request templates 

### ISSUE THREAD

**Issue by akrish4** [ssg8288/DEV_SCRIPT_WOC_2020#14]
Hi @ssg8288 
### You might have seen these templates before while opening a issue or pull request 
![issue1](https://user-images.githubusercontent.com/61831021/103370827-dc644800-4af3-11eb-8acd-e16ab8c70c86.PNG)
![issue2](https://user-images.githubusercontent.com/61831021/103370828-de2e0b80-4af3-11eb-838f-05f565b2113c.PNG)
![github1](https://user-images.githubusercontent.com/61831021/103370830-dff7cf00-4af3-11eb-9061-94c99891845f.PNG)
These are the templates that help maintainers understand about the issue in detail  
When ever a perosn opens a issue he/she needs to select whether it is a bug issue or feature issue , similarly when open a pull reuqest theye need to give a detail abt the PR and need to checklist few things which makes easy for a maintainer to understand and check accordingly.

Let me know if you want to add this feature to your repository ?

Kindly assign me 

If you want to check this feature you go through  [this](https://github.com/akrish4/Learn-By-Write/issues/new/choose)

**Comment by akrish4** [comment]
Kindly note this is feature update for your github repository

**Comment by ssg8288** [comment]
@akrish4 thank you for your interest but I think it is not required as Already the issues are self explanatory and before assigning some one I give them the instructions and I have a Contribution.md file in my repo. Hence, not required thank you. You can check the other issues posted and contribute for the same.
