### ISSUE TITLE
README Template Awesome Looking Shields

### ISSUE THREAD

**Issue by akrish4** [ssg8288/DEV_SCRIPT_WOC_2020#15]
Hi @ssg8288 
### Kindly assign me this issue , if you are interested in beautifying the README file like this 

![readme1](https://user-images.githubusercontent.com/61831021/103407222-dd44ba80-4b83-11eb-9581-7713a61a68be.PNG)

**Comment by ssg8288** [comment]
assigned

> 
> 
> Hi @ssg8288
> ### Kindly let me know if you would like to add these below shown badges in this project readme file?
> ### Kindly assign me this issue , if you are interested in beautifying the README file like this
> 
> ![readme1](https://user-images.githubusercontent.com/61831021/103407222-dd44ba80-4b83-11eb-9581-7713a61a68be.PNG)

assigned

**Comment by akrish4** [comment]
#16 
I have worked on it @ssg8288

**Comment by ssg8288** [comment]
he did this by creating a new or  #16 hence it is resolved

**Comment by akrish4** [comment]
> he did this by creating a new issue #16 hence it is a duplicate of the same issue

This is the only issue opened for this pr 
how is it duplicate 
#16 is pr 
#15 is issue

**Comment by ssg8288** [comment]
the contributor button is not working on clicking its giving a 404 error see it and resolve it @akrish4

**Comment by akrish4** [comment]
> the contributor button is not working on clicking its giving a 404 error see it and resolve it @akrish4

resolved @ssg8288

**Comment by akrish4** [comment]
#17 
resolved and  merged
