### ISSUE TITLE
The Block diagram of Crawler circuit need to be updated

### ISSUE THREAD

**Issue by aeyshubh** [ssg8288/DEV_SCRIPT_WOC_2020#22]
**Describe the bug**
I have just observed that the crawler circuit in Readme.md file has a bug that i would like to solve. 
issue: There are two outputs going from the battery to the Motor driver and DC motor whereas there should only be one output.

**Comment by aeyshubh** [comment]
Please assign this issue to me @ssg8288 , i will complete this within 2 days 
Thanks

**Comment by ssg8288** [comment]
> 
> 
> Please assign this issue to me @ssg8288 , i will complete this within 2 days
> Thanks

great!!
