### ISSUE TITLE
PR TEMPLATE 

### ISSUE THREAD

**Issue by akrish4** [ssg8288/DEV_SCRIPT_WOC_2020#25]
**Is your feature request related to a problem? Please describe.**
As this repository has issue template , similarly I can add a pr template  

**Describe the solution you'd like**
pull_request.md template for pr , it will give description of the pr and reduces the work of the maintainer in merging and understanding it 

**Describe alternatives you've considered**
one solution , no alternative needed 

**Additional context**

**Comment by ssg8288** [comment]
thank you, but not required

**Comment by ssg8288** [comment]
@akrish4 assigned you the issue you can work on the same 👍🏻

**Comment by ssg8288** [comment]
> 
> 
> @akrish4 assigned you the issue you can work on the same 👍🏻

are you working on this issue???

**Comment by akrish4** [comment]
yes @ssg8288 
thank you assigning

**Comment by akrish4** [comment]
Hi @ssg8288 
Let me know if you could add level 2 label instead of level 1 ,  it would help me too 
Thank you

**Comment by ssg8288** [comment]
> 
> 
> Hi @ssg8288
> Let me know if you could add level 2 label instead of level 1 , it would help me too
> Thank you

no level 2 can't be added as it is for major documentation or wiki stuff, whereas, what you are doing is of the order of level 1 tag i.e. minor documentation work. So, can't change it as per dwoc maintainer's T&c*

**Comment by akrish4** [comment]
ok @ssg8288

**Comment by akrish4** [comment]
#28  PR
