### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [ssg8288/DEV_SCRIPT_WOC_2020#29]
Hi @ssg8288 
I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
( config file having a proper message)

Let me know if you are interested in this feature 
Kindly do assign me this issue

For reference, kindly check out: https://github.com/apps/welcome

**Comment by ssg8288** [comment]
> 
> 
> Hi @ssg8288
> I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
> ( config file having a proper message)
> 
> Let me know if you are interested in this feature
> Kindly do assign me this issue
> 
> For reference, kindly check out: https://github.com/apps/welcome

Kindly, always refer to the closed issues before creating a new one already a similar type of issue has been closed. - _ -
