### ISSUE TITLE
Minor Bug fix

### ISSUE THREAD

**Issue by ssg8288** [ssg8288/DEV_SCRIPT_WOC_2020#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aeyshubh** [comment]
Hi, i just found a bug in which the data is directly sent to Arduino whereas, their has to be a module in between to do soo. PLease assign me I will do this

**Comment by ssg8288** [comment]
assigned

> 
> 
> Hi, i just found a bug in which the data is directly sent to Arduino whereas, their has to be a module in between to do soo. PLease assign me I will do this
