### ISSUE TITLE
DOCUMENTATION INTERNET BASED NAVIGATION AND CONTROL WITH BLOCK DIAGRAM AND CIRCUIT DESIGNING

### ISSUE THREAD

**Issue by ssg8288** [ssg8288/DEV_SCRIPT_WOC_2020#5]
@dwoc

- [ ]would require documentation work for  internet-based navigation and control

**Comment by aeyshubh** [comment]
Hello, i would like to work on this issue and you will just love my writings.
P.S i would like to have some more information from the developer .
My Twitter : https://twitter.com/shubham_patel21
Email: shubhamashishpatel@gmail.com

**Comment by ssg8288** [comment]
> 
> 
> Hello, i would like to work on this issue and you will just love my writings.
> P.S i would like to have some more information from the developer .
> My Twitter : https://twitter.com/shubham_patel21
> Email: [shubhamashishpatel@gmail.com](mailto:shubhamashishpatel@gmail.com)

great looking forward for your contribution in this project you are in

**Comment by aeyshubh** [comment]
@ssg8288 can i know some more info about what thing should i include in the documentation. Maybe a google meet for half an hour would work .

**Comment by ssg8288** [comment]
> 
> 
> @ssg8288 can i know some more info about what thing should i include in the documentation. Maybe a google meet for half an hour would work .

yea sure we can talk on this issue over discord this is the link to dwoc chat [!link](https://discord.com/channels/731001496417730611/793093043678085120)   and my discord id is: haspdecrypted looking forward to interacting with u 👍🏻

**Comment by aeyshubh** [comment]
Sure this would work .
