### ISSUE TITLE
DOCUMENTATION FOR INTERNET CONTROLLED ROBOTIC ARM

### ISSUE THREAD

**Issue by ssg8288** [ssg8288/DEV_SCRIPT_WOC_2020#7]
@DWOC

- [ ]DOCUMENTATION FOR INTERNET CONTROLLED ROBOTIC ARM

**Comment by Rishitasharma2001** [comment]
I would like to work on this issue. Please assign it to me. Also, please elaborate on what are your requirements.

**Comment by ssg8288** [comment]
> 
> 
> I would like to work on this issue. Please assign it to me. Also, please elaborate on what are your requirements.

Thanks for showing an interest in this issue @Rishitasharma2001. I have assigned the issue.
 In this documentation for the internet-based controlled robotic arm, these are the following requirements:

- [x]  you need to prepare full documentation on how the whole system will work together with a block diagram & circuit diagram(for circuit diagram you can use fritzing software)
- [x]  listing the components used in this segment so that it's easier for other contributors to work upon the code.
you can take the help of the block diagram I have provided in the readme of this project you get an idea of what was done earlier and what has to be done now. Good luck, feel free to ping me if you are stuck somewhere.

Make sure you fork and star it before contributing to it and see the guidelines.

**Comment by Zircoz** [comment]
You can only use Level 1 or level 2; since documentation of whole project is big enough, use level 2 for this issue.
@ssg8288

**Comment by ssg8288** [comment]
> 
> 
> You can only use Level 1 or level 2; since documentation of whole project is big enough, use level 2 for this issue.
> @ssg8288

okay @Zircoz I updated for the same kindly, check

**Comment by ssg8288** [comment]
@Anu-MADMAX I am updating a documentation file in the robotic arm kindly refer to that and also show your willingness so that I can assign you this issue...I will also help you out as I will also contribute to it so that its easier for you to work on the code.

**Comment by AnuSharma1729** [comment]
I'm interested .. assign it to me pls

**Comment by ssg8288** [comment]
> 
> 
> I'm interested .. assign it to me pls

you are in.

**Comment by ssg8288** [comment]
its completed now you can have a look of what the circuit diagram was like  to be !
