### ISSUE TITLE
Minor Changes or bugs

### ISSUE THREAD

**Issue by ssg8288** [ssg8288/DEV_SCRIPT_WOC_2020#8]
- [x] check for any bugs or code simplicity @dwoc

**Comment by akrish4** [comment]
Hi @ssg8288  
there is a **typo** **error** / **bug** in the contributing file , the link to `code of conduct file` is redirected to some other's repository which actually is a forked repository of this project.
### kindly assign me this issue @ssg8288 
the below shown is the image of `contributing file`.

![bomb_robot1](https://user-images.githubusercontent.com/61831021/103236413-d1ca7700-496a-11eb-939c-c7cf946de350.PNG)

the below shown image is the `code of conduct file`. 



![bomb_robot2](https://user-images.githubusercontent.com/61831021/103236446-edce1880-496a-11eb-9067-1d670f225623.PNG)

**Comment by ssg8288** [comment]
> 
> 
> Hi @ssg8288
> there is a **typo** **error** / **bug** in the contributing file , the link to `code of conduct file` is redirected to some other's repository which actually is a forked repository of this project.
> ### kindly assign me this issue @ssg8288
> 
> the below shown is the image of `contributing file`.
> 
> ![bomb_robot1](https://user-images.githubusercontent.com/61831021/103236413-d1ca7700-496a-11eb-939c-c7cf946de350.PNG)
> 
> the below-shown image is the `code of conduct file`.
> 
> ![bomb_robot2](https://user-images.githubusercontent.com/61831021/103236446-edce1880-496a-11eb-9067-1d670f225623.PNG)

Thanks for pointing this out @akrish4 I have assigned you the issue kindly fork and star it before you move further with it. Goodluck. Kindly, make a note of changes made in the comment while you make a PR.

**Comment by akrish4** [comment]
sure @ssg8288

**Comment by akrish4** [comment]
### Hi @ssg8288 
### i found some typo in this README, let me know i need to rectify it or not , is it a link ? or image ?

![readme_bomb_robot1](https://user-images.githubusercontent.com/61831021/103257808-c1d98400-49b8-11eb-8f04-cdd045805252.PNG)
### and this 

![readme_bomb_robot2](https://user-images.githubusercontent.com/61831021/103257887-0fee8780-49b9-11eb-8104-408cce2e85dd.PNG)

### **these** are links actually not a image link (jpeg/png) , so it won't display a image , only thing can be done is to remove that and it would look like this 

![readme_bomb_robot3](https://user-images.githubusercontent.com/61831021/103258327-8d66c780-49ba-11eb-88d8-8c1b07e99142.PNG)

 let me know whether to need to update like above image or leave it as it is @ssg8288

**Comment by ssg8288** [comment]
> 
> ### Hi @ssg8288
> ### i found some typo in this README, let me know i need to rectify it or not , is it a link ? or image ?
> 
> ![readme_bomb_robot1](https://user-images.githubusercontent.com/61831021/103257808-c1d98400-49b8-11eb-8f04-cdd045805252.PNG)
> ### and this
> 
> ![readme_bomb_robot2](https://user-images.githubusercontent.com/61831021/103257887-0fee8780-49b9-11eb-8104-408cce2e85dd.PNG)
> ### **these** are links actually not a image link (jpeg/png) , so it won't display a image , only thing can be done is to remove that and it would look like this
> 
> ![readme_bomb_robot3](https://user-images.githubusercontent.com/61831021/103258327-8d66c780-49ba-11eb-88d8-8c1b07e99142.PNG)
> 
> let me know whether to need to update like above image or leave it as it is @ssg8288

Yes, these are links not images and your update is fine no problem  you can update it @akrish4 👍

**Comment by akrish4** [comment]
ok thank you @ssg8288

**Comment by akrish4** [comment]
#11

**Comment by ssg8288** [comment]
> 
> 
> #11

is this issue resolved @akrish ??

**Comment by akrish4** [comment]
> > #11
> 
> is this issue resolved @akrish4  ??

yes this is the issue you have just merged (issue resolved)
and you have tagged wrong username (Akrish)

**Comment by ssg8288** [comment]
> 
> 
> > > #11
> > 
> > 
> > is this issue resolved @akrish4  ??
> 
> yes this is the issue you have just merged (issue resolved)
> and you have tagged wrong username (Akrish)

so should I close this issue as well cuz you created a new issue for it which I just merged.

ayee pardon me ;)

**Comment by akrish4** [comment]
> > > > #11
> > > 
> > > 
> > > is this issue resolved @akrish4  ??
> > 
> > 
> > yes this is the issue you have just merged (issue resolved)
> > and you have tagged wrong username (Akrish)
> 
> so should I close this issue as well cuz you created a new issue for it which I just merged.
> 
> ayee pardon me ;)

no , i have opened only 1 issue and this is the only issue which i have linked /referneced in the pull request which you have merged so u need to close this issue which the bug is resolved now, so you can close.

@ssg8288

**Comment by ssg8288** [comment]
> 
> 
> > > > > #11
> > > > 
> > > > 
> > > > is this issue resolved @akrish4  ??
> > > 
> > > 
> > > yes this is the issue you have just merged (issue resolved)
> > > and you have tagged wrong username (Akrish)
> > 
> > 
> > so should I close this issue as well cuz you created a new issue for it which I just merged.
> > ayee pardon me ;)
> 
> no , i have opened only 1 issue and this is the only issue which i have linked /referneced in the pull request which you have merged so u need to close this issue which the bug is resolved now, so you can close.
> 
> @ssg8288

okay great

**Comment by ssg8288** [comment]
The above issue was resolved #11 in this new committed issue and is a duplicate of that same issue hence, I have closed this issue and labelled both the issues with same tags |dwoc |dwoc2020 |level3 |bug
