### ISSUE TITLE
Adding code of conduct and contribution.md

### ISSUE THREAD

**Issue by smriti1313** [ssg8288/DEV_SCRIPT_WOC_2020#9]
I guess it will be a good move to add contribution.md where things like how to start with open source, what are basic commands etc can be included. Also having a code of conduct can help you in rare events.

**Comment by ssg8288** [comment]
@dwoc

- [x] Adding code of conduct and contribution.md

**Comment by ssg8288** [comment]
> 
> 
> I guess it will be a good move to add contribution.md where things like how to start with open source, what are basic commands etc can be included. Also having a code of conduct can help you in rare events.

>> as you said @smriti1313 I feel that's a good idea and I am giving you this opportunity to help and contribute in this repo good luck I will also update the code of conduct and contribution faqs of the basic commands and thanks for pointing this out
